### PR TITLE
Center of semicircle moves away from true center during zooming, and …

### PR DESCRIPTION
**Pull request by hoisingtonp**
…AngularJS failed to import the module ('module' is defined but 'require' isn't). Fixed.

### CODE REVIEW

**Comment by hoisingtonp** [comment]
I'm curious about my "fix" to the _updateCircle method. It places the center of the semicircle where I would expect it to be on my WGS84 map.

**Comment by jieter** [comment]
Thanks for the fixes, I'll merge in a minute.

Please use separate pull requests for unrelated issues next time.

**Comment by jieter** [comment]
released leaflet-semicircle@2.0.1

**Comment by hoisingtonp** [comment]
My bad--I'll use separate pull requests next time. Thanks!

**Pull request merged**
